// ══════════════════ LANGUAGE / TRANSLATIONS ═══════════════════════════════
let LANG = localStorage.getItem('ibbi-lang') || 'en';

const T = {
  en: {
    // Nav
    'nav-biz':'For businesses','nav-infl':'For Influencers','nav-about':'About Us',
    'nav-login':'Log in','nav-register':'Register',
    // Landing hero
    'hero-tag':'The #1 Influencer Marketing Platform',
    'hero-h1':'Like <span>Tinder</span>,<br>but for brands<br>&amp; creators',
    'hero-sub':'IBBI connects verified content creators with businesses that match their niche. Smart matching, real analytics, and multiple campaign types — all in one place.',
    'hero-cta1':'Get Started Free','hero-cta2':'Learn More →',
    'stat-views':'Campaign views','stat-customers':'Customers acquired',
    'stat-collabs':'Collaborations','stat-satisfaction':'Satisfaction rate',
    // Stats strip
    'strip-views':'Total campaign views','strip-customers':'Customers acquired',
    'strip-collabs':'Successful collaborations','strip-paid':'Paid out to creators',
    // How it works
    'hiw-tag':'Simple process','hiw-title':'How IBBI works',
    'hiw-sub':'From registration to your first campaign in minutes. No complexity, no hidden fees.',
    'hiw-1-title':'Create your profile',
    'hiw-1-desc':'Register as a business or influencer. Influencers connect their social accounts for verification — we only read public data.',
    'hiw-2-title':'Get matched',
    'hiw-2-desc':'Our smart algorithm matches businesses with verified creators in the exact same niche — no more cold calls or unnecessary negotiations.',
    'hiw-3-title':'Collaborate &amp; earn',
    'hiw-3-desc':'Run campaigns, track every result in real time, and get paid directly through the platform. Simple, transparent, fast.',
    // Campaign types
    'ct-tag':'Flexibility','ct-title':'4 campaign types for every goal',
    'ct-sub':'Whether you want to pay for results, test with products, or run a fixed deal — IBBI has the right model for you.',
    'ct-aff-desc':'Pay only when the influencer brings real results — sales, clicks, or sign-ups. Zero risk.',
    'ct-aff-tag':'Pay per result','ct-fixed-title':'Fixed Reward',
    'ct-fixed-desc':'Agree on a fixed fee upfront. Great for guaranteed reach and professional content creation.',
    'ct-fixed-tag':'Predictable cost',
    'ct-barter-desc':'Send your product or offer a service in exchange for an honest review or post. Perfect for product launches.',
    'ct-barter-tag':'No cash needed',
    'ct-hybrid-desc':'Combine affiliate + fixed reward for the best of both worlds. Can also include a barter component for product or service exchanges.',
    'ct-hybrid-tag':'Most popular',
    // Landing teasers
    'biz-tease-title':'Find the perfect voice for your brand',
    'biz-tease-sub':'Stop wasting money on influencers with fake followers. Every creator on IBBI is verified — we check real engagement rates, audience authenticity, and niche alignment.',
    'biz-li1':'Advanced filters: niche, followers, engagement rate, platform, country',
    'biz-li2':'Verified influencers only — no fake views, no bought followers',
    'biz-li3':'Pay only for results with affiliate campaigns',
    'biz-li4':'Real-time analytics — track views, clicks, conversions',
    'biz-learn':'Learn more for businesses →',
    'infl-tease-title':'Turn your passion into income',
    'infl-tease-sub':'You don\'t need millions of followers. If you have a loyal audience in a specific niche, IBBI connects you with businesses that genuinely need your voice.',
    'infl-li1':'Browse campaigns that match your exact niche automatically',
    'infl-li2':'Multiple earning models — affiliate, barter, fixed, hybrid',
    'infl-li3':'Track all your earnings and performance in one dashboard',
    'infl-li4':'Direct wallet with payout requests anytime',
    'infl-learn':'Learn more for influencers →',
    // Features
    'feat-tag':'Platform features','feat-title':'Everything you need, nothing you don\'t',
    'feat-sub':'IBBI is built for speed and simplicity. Set up a campaign in minutes, not days.',
    'feat-1-title':'Smart Matching','feat-1-desc':'Algorithm matches businesses with creators based on niche, audience quality, engagement rate, and campaign type preferences.',
    'feat-2-title':'Verified Creators','feat-2-desc':'Every influencer connects their social accounts during registration. We verify real engagement and authenticity.',
    'feat-3-title':'Real-time Analytics','feat-3-desc':'Track views, clicks, conversions, and revenue for every campaign. Performance dashboards for both sides in real time.',
    'feat-4-title':'Built-in Messaging','feat-4-desc':'Negotiate, align, and communicate directly on the platform. No more email chains or lost WhatsApp messages.',
    'feat-5-title':'Direct Wallet','feat-5-desc':'Influencers receive earnings directly to their IBBI wallet. Request payouts anytime — no waiting for manual invoices.',
    'feat-6-title':'Rating System','feat-6-desc':'Both sides rate each other after every collaboration. Builds trust and helps future partners make better decisions fast.',
    // Comparison
    'cmp-tag':'vs. competitors','cmp-title':'Why IBBI beats the alternatives',
    'cmp-sub':'Upfluence, Aspire and Colabstr are expensive, hard to use, and don\'t guarantee results. IBBI was built for small and medium businesses — accessible, transparent, and results-driven.',
    'cmp-col-feature':'Feature','cmp-r1':'Free for influencers','cmp-r1-ibbi':'✓ Always free',
    'cmp-r2':'Pay-per-result model','cmp-r3':'Starting price / month','cmp-r3-ibbi':'Free / Freemium',
    'cmp-r4':'Influencer verification','cmp-r4-ibbi':'✓ Automated',
    'cmp-r5':'Built-in analytics','cmp-r5-ibbi':'✓ Advanced',
    'cmp-r6':'Direct messaging','cmp-r7':'Built-in wallet / payouts',
    'cmp-r8':'Small business friendly','cmp-r8-ibbi':'✓ Core focus','cmp-enterprise':'✗ Enterprise',
    // Landing CTA
    'land-cta-title':'Ready to grow together?',
    'land-cta-sub':'Join hundreds of businesses and creators already collaborating on IBBI. Free to start, no credit card required.',
    'cta-start-free':'Start for free',
    // Pricing
    'price-tag':'Pricing','price-title':'Start free. Scale when you\'re ready.',
    'price-sub':'IBBI uses a freemium model — powerful enough to get your first results for free, with full features when you want to scale.',
    'price-free-name':'Free','price-free-period':'Forever',
    'price-free-f1':'✓ 1 active campaign','price-free-f2':'✓ Advanced analytics',
    'price-free-f3':'✓ Creator discovery','price-free-f4':'✓ Direct messaging',
    'price-free-f5':'✓ Campaign performance reports','price-free-f6':'✓ Built-in wallet &amp; payouts',
    'price-free-btn':'Get started','price-pro-badge':'Popular','price-pro-period':'/month',
    'price-pro-f1':'✓ Unlimited campaigns','price-pro-f2':'✓ Advanced analytics',
    'price-pro-f3':'✓ Priority matching','price-pro-f4':'✓ Campaign performance reports',
    'price-pro-f5':'✓ Dedicated account manager','price-pro-f6':'✓ Custom campaign types',
    'price-pro-f7':'✓ API access','price-pro-btn':'Get Pro',
    // Footer
    'footer-desc':'The smart platform connecting verified content creators with businesses that match their niche. Transparent, data-driven, accessible.',
    'footer-platform':'Platform','footer-campaigns':'Campaigns','footer-legal':'Legal',
    'footer-terms':'Terms of Use','footer-privacy':'Privacy Policy','footer-cookies':'Cookie Policy',
    'footer-rights':'© 2026 IBBI. All rights reserved.',
    'footer-made':'Made with ❤ for creators &amp; brands',
    // For influencers page
    'ip-hero-tag':'For Content Creators','ip-hero-h1':'Turn your passion<br>into real income',
    'ip-hero-sub':'You don\'t need 1M followers. If you have an engaged, loyal audience in a specific niche — businesses are looking for exactly you.',
    'ip-hero-cta1':'Join as Influencer — Free',
    'problem-tag':'The problem','ip-prob-title':'Finding brand deals shouldn\'t be this hard',
    'ip-earn-tag':'Earn your way','ip-earn-title':'4 ways to monetize your audience',
    'ip-earn-sub':'Pick the model that works best for your style and your audience.',
    'ip-aff-desc':'Promote a product with your unique link. Earn a commission for every sale or click you generate. Best for creators with high-converting audiences.',
    'ip-aff-tag':'Commission based',
    'ip-fixed-desc':'Agree on a fee for a post, story, or video. Payment is guaranteed regardless of results. Best for creators with premium content.',
    'ip-fixed-tag':'Guaranteed pay',
    'ip-barter-desc':'Receive a product you\'re genuinely interested in and review it honestly. No cash involved — you pick brands that align with your values and content.',
    'ip-hybrid-desc':'A base fixed fee plus commission. You get a guaranteed minimum plus a bonus for strong performance. Can also be combined with a barter component.',
    'ip-hybrid-tag':'Fixed + commission',
    'ben-tag':'Benefits','ip-ben-title':'Everything built around your success',
    'ip-ben-1t':'Niche-matched campaigns','ip-ben-1d':'Only see campaigns relevant to your content. Fitness creator? Only fitness brands. Food blogger? Only food companies.',
    'ip-ben-2t':'Performance dashboard','ip-ben-2d':'Track views, clicks, conversions, and earnings for every campaign in real time. Know exactly what\'s working.',
    'ip-ben-3t':'Direct wallet &amp; payouts','ip-ben-3d':'All earnings go straight to your IBBI wallet. Request a payout at any time — bank transfer processed within 3 business days.',
    'ip-ben-4t':'Build your reputation','ip-ben-4d':'Every successful collaboration earns you a rating. High-rated influencers get priority matching with top brands.',
    'ip-ben-5t':'Free to join','ip-ben-5d':'Joining IBBI is free — no subscriptions, no hidden fees. We take a small 10% platform commission only on earnings made through the platform.',
    'ip-ben-6t':'Direct communication','ip-ben-6d':'Chat directly with businesses inside the platform. Negotiate terms, ask questions, confirm deliverables — all in one place.',
    'ip-old1-title':'The old way','ip-old1-desc':'Cold DMing businesses that never reply. Getting ignored or offered ridiculous terms. Wasting hours on outreach that leads nowhere — while your content keeps growing.',
    'ip-new1-title':'The IBBI way','ip-new1-desc':'Businesses come to you. Our algorithm shows your profile to brands in your exact niche. One click to accept, built-in negotiation, and payment straight to your wallet.',
    'ip-old2-title':'No transparency','ip-old2-desc':'You never know if a brand is legit. Paid upfront? Risky. Paid after? Often ghosted. No contract, no security, no recourse.',
    'ip-new2-title':'Full protection','ip-new2-desc':'Every business on IBBI is registered and rated by other influencers. See their rating before you commit. Campaign terms are locked in the platform.',
    'ip-cta-title':'Start earning with your content today',
    'ip-cta-sub':'Free to join. Connect your socials, complete your profile, and start receiving campaign invites within 24 hours.',
    'ip-cta-btn':'Create Free Account',
    'ip-niche-tag':'Who is IBBI for','ip-niche-title':'You don\'t need to be famous',
    'ip-niche-sub':'IBBI is built for creators who are deeply connected with a specific community — not just those with the biggest follower counts.',
    'ip-niche-1t':'Fitness & Wellness','ip-niche-1d':'Personal trainers, nutrition coaches, yoga instructors — brands love niche fitness creators with real, engaged followers.',
    'ip-niche-2t':'Food & Lifestyle','ip-niche-2d':'Restaurant reviewers, home cooks, food photographers — local and national food brands are always looking for authentic voices.',
    'ip-niche-3t':'Ecology & Sustainability','ip-niche-3d':'Green living creators, zero-waste advocates — eco-brands specifically seek micro-influencers with passionate, conscious audiences.',
    'ip-niche-4t':'Beauty & Selfcare','ip-niche-4d':'Makeup artists, skincare enthusiasts, nail techs — beauty is one of the highest-paying niches for authentic product reviews.',
    'ip-niche-5t':'Tech & Gaming','ip-niche-5d':'Reviewers, streamers, tutorial makers — tech companies value creators who can explain products to a knowledgeable audience.',
    'ip-niche-6t':'Travel & Adventure','ip-niche-6d':'Travel bloggers, destination photographers — tourism boards and travel brands need real experiences from real explorers.',
    // For businesses page
    'bp-hero-tag':'For Businesses &amp; Brands','bp-hero-h1':'Influencer marketing<br>that actually works',
    'bp-hero-sub':'Stop paying €2,000/month for platforms that don\'t deliver. IBBI connects you with verified creators in your niche — and you pay only for real results.',
    'bp-hero-cta1':'Start for Free','bp-prob-title':'Why most influencer marketing fails',
    'bp-hiw-title':'From signup to first campaign in minutes',
    'bp-step1-title':'Create your business profile',
    'bp-step1-desc':'Sign up, describe your brand and target niche. The more detail you provide, the better our matching works for you.',
    'bp-step2-title':'Discover &amp; invite creators',
    'bp-step2-desc':'Browse our verified creator database. Filter by niche, followers, engagement, and platform. Send invites directly in the app.',
    'bp-step3-title':'Launch &amp; track results',
    'bp-step3-desc':'Create your campaign, set terms and compensation type. Track every view, click, and conversion from your analytics dashboard.',
    'bp-ben-title':'Built for small &amp; medium businesses',
    'bp-ben-sub':'No enterprise contracts. No €2,000/month subscriptions. IBBI gives you the tools of a big platform at a price that makes sense.',
    'bp-ben-1t':'Advanced creator discovery','bp-ben-1d':'Search by niche, platform, follower range, engagement rate, country, and campaign type compatibility. Find exactly who you need.',
    'bp-ben-2t':'Campaign analytics','bp-ben-2d':'Real-time data on views, web visitors, conversions, and customer acquisition costs. Know your ROI for every campaign.',
    'bp-ben-3t':'Fraud protection','bp-ben-3d':'Automated detection of fake followers and bought engagement. Every creator is scored on authenticity before they join the platform.',
    'bp-ben-4t':'Flexible payment models','bp-ben-4d':'Choose from affiliate (pay per result), fixed fee, barter, or hybrid. Match the payment model to your budget and goals.',
    'bp-ben-5t':'Creator ratings','bp-ben-5d':'See ratings left by other businesses before you invite a creator. Community-verified reliability, not just follower counts.',
    'bp-ben-6d':'Message creators directly inside IBBI. Discuss terms, share briefs, review content — no external tools needed.',
    'bp-prob1-t':'Fake engagement','bp-prob1-d':'You pay a creator, they post, the numbers look great — but those views and likes were bought. No real customers, no real ROI. Just wasted budget.',
    'bp-sol1-t':'Verified only','bp-sol1-d':'Every IBBI influencer connects their social accounts for verification. We automatically flag suspicious engagement rates, bought followers, and inauthentic growth patterns.',
    'bp-prob2-t':'Wrong audience','bp-prob2-d':'The biggest influencer in your country isn\'t necessarily the right one for your brand. Reach without relevance is just noise — and expensive noise at that.',
    'bp-sol2-t':'Niche matching','bp-sol2-d':'Filter by niche, platform, follower count, engagement rate, location, and campaign type. Find creators whose audience actually wants your product.',
    'bp-prob3-t':'Pay upfront, get nothing','bp-prob3-d':'Traditional influencer deals require payment before delivery. Many creators ghost, deliver poor content, or simply don\'t drive the results they promised.',
    'bp-sol3-t':'Affiliate campaigns','bp-sol3-d':'With IBBI\'s affiliate model, you pay only when an influencer delivers actual results — clicks, sign-ups, or purchases. Zero risk, maximum ROI.',
    'bp-cta-title':'Ready to find your perfect creators?',
    'bp-cta-sub':'Join businesses already growing through authentic influencer partnerships on IBBI. Start free, no credit card required.',
    'bp-cta-btn':'Create Business Account','bp-cta-login':'Already have account',
    // About us
    'au-hero-tag':'Our Story','au-hero-h1':'We\'re solving a<br>€2 billion problem',
    'au-hero-sub':'Small businesses can\'t afford enterprise influencer platforms. Influencers struggle to find trustworthy brand deals. IBBI was built to fix both.',
    'au-miss-tag':'Our mission','au-miss-title':'Make influencer marketing accessible to everyone',
    'au-miss-p1':'The influencer marketing industry is worth over €20 billion globally — yet most of its value is locked behind expensive enterprise tools accessible only to large corporations.',
    'au-miss-p2':'Small and medium businesses have great products but no marketing team. Micro and mid-size influencers have loyal audiences but no easy way to monetize them. IBBI bridges that gap.',
    'au-miss-p3':'We believe that a local fitness brand should be able to collaborate with a local fitness creator as easily as Nike works with Cristiano Ronaldo. That\'s what we\'re building.',
    'au-prob-tag':'The problem we solve','au-prob-title':'Two sides, one broken system',
    'au-prob-sub':'Both businesses and influencers have been underserved by existing solutions. We listened to both sides before building anything.',
    'au-val-tag':'Our values','au-val-title':'What we stand for',
    'val-1t':'Transparency','val-1d':'We believe every collaboration should be based on real data. No hidden metrics, no fake numbers, no surprises.',
    'val-2t':'Simplicity','val-2d':'Powerful doesn\'t have to mean complicated. Every feature on IBBI is designed to be understood and used by anyone in a few seconds.',
    'val-3t':'Fairness','val-3d':'Both businesses and creators deserve fair terms. IBBI is the neutral ground where both sides win.',
    'val-4t':'Results first','val-4d':'We measure success by whether our users grow — not by how many features we ship. Outcomes over activity.',
    'val-5t':'Trust','val-5d':'Every verification step, every rating system, every fraud check — it\'s all built to make every interaction trustworthy.',
    'val-6t':'Accessibility','val-6d':'Great marketing tools shouldn\'t require a €2,000 budget. IBBI is built for businesses of any size, in any market.',
    'au-road-tag':'Roadmap','au-road-title':'Where we\'re headed',
    'au-road-sub':'We\'re just getting started. Here\'s what\'s coming to IBBI in the next phases.',
    'au-quote-text':'"Like Tinder,<br>but for brands<br>&amp; creators"',
    'au-quote-sub':'Our founding concept — smart matching between the right partners',
    'au-biz-pain-h':'Business pain points','au-infl-pain-h':'Influencer pain points',
    'au-biz-p1-t':'Authenticity distrust','au-biz-p1-d':'How do you know an influencer\'s followers are real? Fake metrics waste thousands in budget with zero ROI.',
    'au-biz-p2-t':'High platform costs','au-biz-p2-d':'Existing platforms start at €2,000/month — completely out of reach for most small businesses.',
    'au-biz-p3-t':'Poor matching','au-biz-p3-d':'Finding an influencer who reaches your exact niche audience is time-consuming, expensive, and often inaccurate.',
    'au-infl-p1-t':'Getting ignored','au-infl-p1-d':'Small and mid-size creators spend hours on cold outreach to businesses that never reply. Demotivating and time-consuming.',
    'au-infl-p2-t':'Payment risk','au-infl-p2-d':'No secure payment system means creators often do the work and never get paid. No contract enforcement, no protection.',
    'au-infl-p3-t':'No analytics','au-infl-p3-d':'Most creators have no idea which of their collaborations actually drive results. No data means no leverage for better deals.',
    'au-road-p1-t':'Phase 1 — Now','au-road-p1-d':'Core platform: registration, campaign creation, creator discovery, messaging, basic analytics, wallet, and payouts.',
    'au-road-p2-t':'Phase 2 — Q3 2026','au-road-p2-d':'Advanced analytics dashboard, social auth (Google, Meta), automated performance reports, mobile app.',
    'au-road-p3-t':'Phase 3 — Q1 2027','au-road-p3-d':'AI-powered campaign suggestions, multi-language support, enterprise tier, API for custom integrations.',
    'au-road-p4-t':'Phase 4 — 2027+','au-road-p4-d':'International expansion, marketplace for content assets, advanced fraud detection AI, creator academy.',
    'au-cta-title':'Join us on this journey',
    'au-cta-sub':'Whether you\'re a creator looking to monetize your passion, or a business looking for authentic marketing — IBBI is for you.',
    // Auth
    'reg-tag':'Create Account','reg-title':'Who are you joining as?',
    'reg-sub':'Choose your role — you can always switch later in settings.',
    'reg-infl-desc':'I create content and want to collaborate with brands for campaigns &amp; rewards.',
    'reg-infl-btn':'Join as Influencer','reg-biz-name':'Business',
    'reg-biz-desc':'I represent a brand or company and want to find influencers for campaigns.',
    'reg-biz-btn':'Join as Business',
    'reg-login-link':'Already have an account? <a onclick="go(\'login\')" style="color:var(--blue);cursor:pointer;font-weight:600">Sign in</a>',
    'login-title':'Welcome back','login-sub':'Sign in to your account','login-btn':'Sign In',
    'login-signup-link':'Don\'t have an account? <a onclick="go(\'signup-role\')" style="color:var(--blue);cursor:pointer;font-weight:600">Sign up free</a>',
    // App portal topbar
    'app-biz-portal':'Business <span style="color:var(--blue)">Portal</span>',
    'app-infl-portal':'Influencer <span style="color:var(--blue)">Portal</span>',
    // Dashboard stats
    'd-active-camps':'Active Campaigns','d-total-reach':'Total Reach',
    'd-conversions':'Conversions','d-total-spent':'Total Spent',
    'd-total-earnings':'Total Earnings','d-followers':'Followers',
    'd-avg-er':'Avg. Engagement','d-across-camps':'Across all campaigns',
    'd-all-time':'All time','d-camp-spend':'Campaign spend',
    'd-lifetime':'Lifetime earnings','d-across-plat':'Across all platforms',
    'd-er-label':'Engagement rate','d-total-convs':'Total Conversions',
    'd-roas':'Return on ad spend','d-camp-budget':'Campaign budget used',
    // Dashboard sections
    'd-recent-camps':'Recent Campaigns','d-view-all':'View All',
    'd-quick-actions':'Quick Actions','d-create-camp':'Create Campaign',
    'd-discover-infls':'Discover Influencers','d-view-analytics':'View Analytics',
    'd-wallet-bal':'Wallet Balance','d-avail-bal':'Available balance',
    'd-top-up':'Top Up','d-top-infls':'Top Influencers This Month',
    'd-discover-more':'Discover More','d-my-camps':'My Campaigns',
    'd-browse-more':'Browse More','d-browse-camps':'Browse Campaigns',
    'd-edit-profile':'Edit Profile','d-wallet-lbl':'Wallet',
    'd-avail-withdraw':'Available to withdraw','d-withdraw':'Withdraw',
    'd-rec-camps':'Recommended Campaigns','d-see-all':'See All',
    'd-apply-now':'Apply Now','d-due':'Due',
    // Table headers
    'th-campaign':'Campaign','th-type':'Type','th-status':'Status',
    'th-reach':'Reach','th-spent':'Spent','th-brand':'Brand',
    'th-reward':'Reward','th-conversions':'Conversions','th-roas':'ROAS',
    // Campaigns
    'c-my-camps':'My Campaigns','c-total-label':'total campaigns',
    'c-new':'New Campaign','c-create-new':'Create New Campaign',
    'c-launch':'Launch Campaign','c-draft':'Save as Draft','c-cancel':'Cancel',
    'c-form-name':'Campaign Name','c-form-type':'Campaign Type',
    'c-form-budget':'Total Budget (€)','c-form-reward':'Reward per Influencer (€)',
    'c-form-niche':'Target Niche','c-form-deadline':'Deadline',
    'c-form-brief':'Campaign Brief',
    'c-form-commission':'Commission Rate (%)','c-form-barter-desc':'Barter Product / Service',
    'c-form-desc':'Campaign Description','c-form-payout-metric':'Payout Metric',
    'c-form-target-niches':'Target Niches','c-form-niche-sub':'select all that apply',
    'c-form-deadline-sub':'optional — runs until budget depleted',
    'c-form-combine-types':'Combine Campaign Types','c-form-combine-sub':'select at least 2',
    'c-applied-badge':'Applied','c-chat':'Chat','c-ask':'Ask',
    'c-rate-brand':'★ Rate Brand','c-infl-available':'campaigns available',
    'c-applied-count':'applied','c-view-campaigns':'View Campaigns',
    // Discover
    'dis-infls-title':'Discover Influencers','dis-brands-title':'Discover Brands',
    'dis-infls-sub':'verified creators found','dis-brands-sub':'actively looking for collaborations',
    'f-all-types':'All Types','f-all-industries':'All Industries',
    'f-all-niches':'All Niches','f-all-sizes':'All Sizes','f-any-platform':'Any Platform',
    'f-search-camps':'Search campaigns…','f-search-brands':'Search brands…',
    'f-search-infls':'Search name or @handle…',
    'f-sort-followers':'Sort: Followers ↓','f-sort-er':'Sort: ER ↓',
    'f-sort-rating':'Sort: Rating ↓','f-sort-price':'Sort: Price ↑',
    // Infl card labels
    'ic-campaigns':'Campaigns','ic-rating':'Rating','ic-message':'Message','ic-invite':'Invite',
    // Analytics
    'an-total-reach':'Total Reach','an-total-convs':'Total Conversions',
    'an-total-spent':'Total Spent','an-roas':'ROAS',
    'an-perf-title':'Monthly Reach & Conversions','an-mix-title':'Campaign Mix',
    'an-camp-title':'Campaign Performance Comparison',
    'an-infl-title':'Influencer Performance',
    // Wallet
    'w-avail-bal':'Available Balance','w-total-topped':'Total topped up:',
    'w-top-up-title':'Top Up Wallet','w-topup-sub':'Funds are added instantly after payment. Minimum €10.',
    'w-pay-card':'Pay with Card →','w-request':'Request Payout',
    'w-active-camps':'Active campaigns',
    // Conversations
    'msg-conversations':'Conversations','msg-no-convs':'No conversations yet.',
    'msg-send':'Send','msg-placeholder':'Type a message…',
    'msg-active-infl':'Active influencer','msg-active-biz':'Active business',
    'msg-no-convs-biz':'No conversations yet.<br>Invite an influencer to start.',
    'msg-select-conv':'Select a conversation','msg-active-brand':'Brand',
    'msg-no-msgs-yet':'No messages yet. Say hello! 👋',
    // Messages filter tabs
    'msg-filter-all':'All','msg-filter-unread':'Unread','msg-filter-starred':'Starred','msg-filter-creators':'Creators',
    'msg-collaborate':'Collaborate','msg-attach-title':'Attach file',
    // FindUser modal
    'fu-placeholder':'Find a creator, brand or @handle…',
    'fu-filters-btn':'Filters','fu-filter-all':'All','fu-filter-influencers':'Influencers','fu-filter-brands':'Brands',
    'fu-recent-searches':'Recent searches','fu-popular-cats':'Popular categories',
    'fu-recommended':'Recommended for you','fu-results-for':'Results for',
    'fu-searching':'Searching…','fu-no-results':'Nothing found. Try a different keyword.',
    'fu-loading-recommended':'Loading recommendations…','fu-login-required':'Log in to search.',
    'fu-nav-hint':'navigate','fu-open-hint':'open','fu-close-hint':'close',
    'fu-invite-email':'Invite by email','fu-write-btn':'Write',
    'fu-role-creator':'Creator','fu-role-brand':'Brand','fu-followers-label':'followers',
    // App tabs
    'tab-performance':'Performance','tab-campaigns':'Campaigns','tab-collaboration':'Collaboration',
    'tab-revenue':'Revenue','tab-overview':'Overview','tab-transactions':'Transactions','tab-payouts':'Payouts',
    // Status badges
    'status-active':'Active','status-paused':'Paused','status-completed':'Completed','status-draft':'Draft',
    // Campaigns detail & misc
    'c-applications':'Applications','c-loading':'Loading…','c-select-conv':'Select a conversation',
    'c-applicants':'applicants','c-reward-label':'Reward','c-due-label':'Due',
    // Profile
    'prof-edit-btn':'Edit Profile','prof-save':'Save Changes','prof-cancel':'Cancel',
    'prof-edit-biz':'Edit Company Profile','prof-edit-infl':'Edit Your Profile',
    'prof-about':'About','prof-about-me':'About Me',
    'prof-about-placeholder':'Click Edit Profile to add a company description.',
    'prof-active-camps':'Active Campaigns','prof-no-active-camps':'No active campaigns yet.',
    'prof-reviews':'Reviews from Influencers','prof-no-reviews':'No reviews yet.',
    'prof-camps-run':'Campaigns Run','prof-infls-worked':'Influencers Worked With',
    'prof-rating-label':'Rating','prof-reviews-count':'Reviews',
    'prof-followers':'Followers','prof-avg-er':'Avg. ER','prof-campaigns':'Campaigns',
    'prof-connected-platforms':'Connected Platforms','prof-no-platforms':'No platforms added yet.',
    'prof-add-platforms':'Add platforms in Settings →',
    'prof-campaign-stats':'Campaign Stats','prof-pricing':'Pricing',
    'prof-price-per-post':'Price range per post','prof-no-pricing':'No pricing set yet.',
    'prof-set-price':'Set price range in Settings →',
    'prof-camps-applied':'Campaigns Applied','prof-camps-completed':'Campaigns Completed',
    'prof-total-earnings':'Total Earnings','prof-avg-er-rate':'Avg. Engagement Rate',
    'prof-verified':'✓ Verified','prof-loading':'Loading your profile…',
    // Settings field labels
    'fld-company-name':'Company Name','fld-industry':'Industry','fld-website':'Website',
    'fld-country':'Country','fld-phone':'Phone','fld-work-email':'Work Email',
    'fld-full-name':'Full Name','fld-username':'Username','fld-niche':'Niche',
    'fld-price-range':'Price Range (e.g. €200–500)','fld-bio':'Bio',
    'fld-about-company':'About your company','fld-er':'Engagement Rate (%)','fld-followers':'Follower Count',
    'fld-first-name':'First Name','fld-last-name':'Last Name','fld-email':'Email','fld-primary-niche':'Primary Niche',
    // Settings sections
    'set-title':'Account Settings','set-company-profile':'Company Profile','set-personal-info':'Personal Info',
    'set-notifications':'Notifications','set-security':'Security',
    'set-change-pwd':'Change Password','set-enable-2fa':'Enable 2FA',
    'set-danger-zone':'Danger Zone','set-delete-account':'Delete Account',
    'set-delete-warn-biz':'Deleting your account is irreversible and will remove all campaign data.',
    'set-delete-warn-infl':'Deleting your account will remove all your data permanently.',
    'set-loading':'Loading your settings…',
    // Settings notification labels
    'notif-new-apps':'New influencer applications','notif-new-apps-desc':'Notify when influencers apply to campaigns',
    'notif-milestones':'Campaign milestones','notif-milestones-desc':'Reach and conversion milestone alerts',
    'notif-messages':'Message notifications','notif-msg-biz-desc':'New messages from influencers',
    'notif-weekly':'Weekly reports','notif-weekly-desc':'Performance summary every Monday',
    'notif-invites':'New campaign invitations','notif-invites-desc':'Brands that invite you directly',
    'notif-payment':'Payment received','notif-payment-desc':'When earnings are deposited',
    'notif-deadline':'Campaign deadline reminders','notif-deadline-desc':'48h before deadline',
    'notif-weekly-perf':'Weekly performance report','notif-weekly-perf-desc':'Summary every Monday',
    'notif-msg-infl-desc':'New messages from brands',
    // Wallet extra
    'w-cancel':'Cancel','w-low-balance':'⚠ Low balance — top up to keep campaigns running',
    'w-top-up-btn':'+ Top Up','w-total-spent-lbl':'Total Spent','w-total-topup-lbl':'Total Topped Up',
    'w-lifetime':'Lifetime','w-all-time':'All time','w-funded':'Funded',
    'w-camps-run':'Campaigns Run','w-monthly-spend':'Monthly Spend','w-spend-by-type':'Spend by Campaign Type',
    'w-date':'Date','w-description':'Description','w-amount':'Amount','w-status-col':'Status',
    'w-total-earned-lbl':'Total Earned','w-total-withdrawn-lbl':'Total Withdrawn','w-to-bank':'To bank',
    'w-pending-label':'Pending','w-processing':'Processing','w-completed':'Completed',
    'w-monthly-earnings':'Monthly Earnings','w-payout-methods':'Payout Methods',
    'w-add-iban-section':'Add Bank Account (IBAN)','w-no-transactions':'No transactions yet.',
    'w-request-withdrawal':'Request Withdrawal','w-withdraw-btn':'Withdraw',
    'w-payout-history':'Payout History','w-no-payouts':'No payouts yet.','w-requested-badge':'Requested',
    'w-add-iban-btn':'Add IBAN','w-camps-label':'Campaigns','w-iban-transfer':'IBAN Bank Transfer',
    'w-pending-prefix':'Pending:','w-processing-suffix':'(processing)',
    'w-min-info':'Minimum: €50 · Processing: 2–3 business days · Available:',
    // Campaign detail modal
    'cd-no-brief':'No brief provided.','cd-payout-method':'Payout Method',
    'cd-discount-code':'Discount Code + Commission','cd-per-views':'Per Views',
    'cd-commission-rate':'Commission Rate','cd-reward-per-infl':'Reward per Influencer',
    'cd-product-service':'Product / Service','cd-combined-types':'Combined Types',
    'cd-fixed-reward':'Fixed Reward','cd-barter-details':'Barter Details',
    'cd-budget':'Budget','cd-deadline-label':'Deadline','cd-niches':'Niches',
    'cd-brief-label':'Brief','cd-close':'Close','cd-applied':'✓ Applied',
    // Analytics extra
    'an-camps-done':'Campaigns Done','an-total-collabs':'Total collaborations',
    // Discover filters
    'dis-no-infls':'No influencers found','dis-no-infls-sub':'Try adjusting your filters',
    'dis-no-brands':'No brands found','dis-no-brands-sub':'Try adjusting your filters',
    'dis-brands-found':'brands found',
    // Influencer modal
    'modal-followers':'Followers','modal-eng-rate':'Eng. Rate','modal-campaigns':'Campaigns',
    'modal-smart-match':'Smart Match Score','modal-platforms':'Platforms',
    'modal-price-range':'Estimated price range',
    'modal-match-excellent':'Excellent fit for your active campaigns',
    'modal-match-good':'Good match — worth considering',
    'modal-match-moderate':'Moderate match with your campaigns',
    'modal-message':'Message','modal-invite':'Invite',
    // Brand card
    'brand-active-camp':'active campaign','brand-active-camps':'active campaigns',
    // Toast messages
    'toast-profile-saved':'Profile saved!','toast-company-req':'Company name required.',
    // Campaign modal
    'camp-modal-title':'Create Campaign','camp-modal-sub':'Select a type, then fill in the details',
    'camp-loading-apps':'Loading applications…',
    // Notifications panel
    'notif-panel-heading':'Notifications','notif-mark-all-read':'Mark all read',
    'notif-none':'No notifications yet','btn-close':'Close',
    // Change password modal
    'cp-subtitle':'Enter and confirm your new password.',
    'cp-update-btn':'Update Password',
    // 2FA modal
    'twofa-subtitle':'Scan the QR code with your authenticator app (Google Authenticator, Authy, etc.)',
    'twofa-verify-btn':'Verify & Enable',
    // Rating modal
    'rating-title':'Rate your collaboration','rating-click-star':'Click a star to rate',
    'rating-submit-btn':'Submit Rating',
    // Applications drawer
    'app-no-apps':'No applications yet.','app-no-rating':'No rating yet',
    'app-accept':'Accept','app-reject':'Reject',
    // Update stats modal
    'us-title':'Update Campaign Stats','us-reach-lbl':'Total Reach',
    'us-conv-lbl':'Conversions','us-save-btn':'Save Stats',
    // Role picker
    'role-pick-title':'Choose Account Type','role-pick-sub':'You have both account types. How do you want to sign in?',
    'role-business':'Business','role-influencer':'Influencer',
    // Transaction descriptions
    'txn-topup':'Wallet top-up','txn-camp-fund':'Campaign funded','txn-transaction':'Transaction',
    'txn-earnings':'Earnings','txn-withdrawal':'Withdrawal',
    // Auth button states
    'btn-signing-in':'Signing in…','btn-creating-acc':'Creating account…',
    'infl-signup-btn-lbl':'Continue to Verification →',
    'biz-signup-btn-lbl':'Create Account & Enter Dashboard →',
    'btn-complete-setup':'Complete Setup & Go to Dashboard →',
    'btn-setting-up':'Setting up…',
    // Generic button states
    'btn-saving':'Saving…','btn-updating':'Updating…',
    'btn-verifying':'Verifying…','btn-disabling':'Disabling…',
    'btn-stripe-redirect':'Redirecting to Stripe…','btn-pay-card':'Pay with Card →',
    'twofa-disable-btn':'Disable 2FA','twofa-manage-btn':'Manage 2FA',
    // Validation errors
    'err-fill-fields':'Please fill in all fields.',
    'err-pwd-length':'Password must be at least 8 characters.',
    'err-fill-required':'Please fill in all required fields.',
    'err-accept-terms':'Please accept the Terms of Service.',
    'err-acct-exists-infl':'Influencer account already exists for this email. Sign in via login.',
    'err-acct-exists-biz':'Business account already exists for this email. Sign in via login.',
    'err-name-username':'Name and username required.',
    'err-camp-name-brief':'Campaign name and brief are required.',
    'err-pwds-no-match':'Passwords do not match.',
    'err-6digit-code':'Enter the 6-digit code.',
    // Campaign wizard
    'wiz-step-type':'Type','wiz-step-details':'Details','wiz-step-budget':'Budget',
    'wiz-step-audience':'Audience','wiz-step-schedule':'Schedule','wiz-step-lbl':'Step',
    'wiz-back':'Back','wiz-next':'Continue','wiz-save-draft':'Save draft','wiz-launch':'Launch',
    'wiz-s1-title':'What type of campaign?','wiz-s1-sub':'Choose a collaboration model that fits your goal.',
    'wiz-s2-title':'Campaign details','wiz-s2-sub':'Give your campaign a clear name and brief so creators know what you need.',
    'wiz-brief-hint':'characters','wiz-brief-ph':'Describe what you want creators to do, what content to create, and any specific requirements…',
    'wiz-s3-title':'Budget & payout','wiz-s3-sub':'Set your budget and how you will pay creators.',
    'wiz-cpm':'CPM rate (€ per 1 000 views)','wiz-product-value':'Product value (€)',
    'wiz-max-creators':'Max number of creators','wiz-payout-method':'Payout method',
    'wiz-budget-info':'Budget is indicative. Actual spend depends on the number of accepted creators.',
    'wiz-s4-title':'Audience & targeting','wiz-s4-sub':'Define the creator profile and audience you want to reach.',
    'wiz-niches':'Niches','wiz-niches-hint':'Select all that apply',
    'wiz-audience-size':'Audience size (followers)','wiz-geo':'Geographic targeting',
    'wiz-s5-title':'Schedule & deliverables','wiz-s5-sub':'Set timeline and expected content output.',
    'wiz-start-date':'Start date','wiz-platforms':'Platforms','wiz-deliverables':'Deliverables',
    'wiz-launch-info':'Campaign will be reviewed and activated within 24 hours.',
    'wiz-type-affiliate':'Affiliate','wiz-type-affiliate-sub':'Pay per result',
    'wiz-type-fixed':'Fixed reward','wiz-type-fixed-sub':'Fixed fee',
    'wiz-type-barter':'Barter','wiz-type-barter-sub':'Product exchange',
    'wiz-type-hybrid':'Hybrid','wiz-type-hybrid-sub':'Combined model',
    'wiz-payout-discount':'Discount code','wiz-payout-views':'CPM / Views',
    'wiz-payout-bank':'Bank transfer','wiz-payout-crypto':'Crypto',
    'wiz-camp-name-label':'Campaign name','wiz-camp-brief-label':'Brief',
    'wiz-budget-label':'Total budget (€)','wiz-commission-label':'Commission rate (%)',
    'wiz-fixed-fee-label':'Fixed fee per creator (€)',
  },
  sk: {
    // Nav
    'nav-biz':'Pre firmy','nav-infl':'Pre influencerov','nav-about':'O nás',
    'nav-login':'Prihlásiť sa','nav-register':'Registrovať sa',
    // Landing hero
    'hero-tag':'Platforma č. 1 pre influencer marketing',
    'hero-h1':'Ako <span>Tinder</span>,<br>ale pre značky<br>&amp; tvorcov',
    'hero-sub':'IBBI spája overených tvorcov obsahu s firmami, ktoré zodpovedajú ich niche. Inteligentné párovanie, skutočná analytika a viacero typov kampaní — všetko na jednom mieste.',
    'hero-cta1':'Začni zadarmo','hero-cta2':'Zistiť viac →',
    'stat-views':'Zobrazenia kampaní','stat-customers':'Získaní zákazníci',
    'stat-collabs':'Spolupráce','stat-satisfaction':'Miera spokojnosti',
    // Stats strip
    'strip-views':'Celkové zobrazenia kampaní','strip-customers':'Získaní zákazníci',
    'strip-collabs':'Úspešné spolupráce','strip-paid':'Vyplatené tvorcom',
    // How it works
    'hiw-tag':'Jednoduchý proces','hiw-title':'Ako IBBI funguje',
    'hiw-sub':'Od registrácie po prvú kampaň za niekoľko minút. Žiadna zložitosť, žiadne skryté poplatky.',
    'hiw-1-title':'Vytvor si profil',
    'hiw-1-desc':'Registruj sa ako firma alebo influencer. Influenceri prepoja sociálne siete na overenie — čítame len verejné údaje.',
    'hiw-2-title':'Nájdi zhodu',
    'hiw-2-desc':'Náš inteligentný algoritmus spája firmy s overenými tvorcami v rovnakom niche — žiadne cold calls ani zbytočné dohadovania.',
    'hiw-3-title':'Spolupracuj &amp; zarábaj',
    'hiw-3-desc':'Spúšťaj kampane, sleduj každý výsledok v reálnom čase a zarábaj priamo cez platformu. Jednoducho, transparentne, rýchlo.',
    // Campaign types
    'ct-tag':'Flexibilita','ct-title':'4 typy kampaní pre každý cieľ',
    'ct-sub':'Či chceš platiť za výsledky, testovať s produktmi, alebo spustiť fixnú dohodu — IBBI má správny model práve pre teba.',
    'ct-aff-desc':'Plať len vtedy, keď influencer prinesie skutočné výsledky — predaje, kliknutia alebo registrácie. Nulové riziko.',
    'ct-aff-tag':'Platba za výsledok','ct-fixed-title':'Fixná odmena',
    'ct-fixed-desc':'Dohovor sa na fixnom poplatku vopred. Ideálne pre garantovaný dosah a profesionálnu tvorbu obsahu.',
    'ct-fixed-tag':'Predvídateľné náklady',
    'ct-barter-desc':'Pošli produkt alebo ponúkni službu výmenou za poctivú recenziu alebo príspevok. Ideálne pre uvedenie produktov na trh.',
    'ct-barter-tag':'Bez hotovosti',
    'ct-hybrid-desc':'Spoj affiliate + fixnú odmenu pre to najlepšie z oboch svetov. Môžeš ho tiež skombinovať s barterom pre výmenu produktov alebo služieb.',
    'ct-hybrid-tag':'Najobľúbenejší',
    // Landing teasers
    'biz-tease-title':'Nájdi dokonalý hlas pre svoju značku',
    'biz-tease-sub':'Prestaň míňať peniaze na influencerov s falošnými sledovateľmi. Každý tvorca na IBBI je overený — kontrolujeme skutočnú mieru angažovanosti, autentičnosť publika a zacielenie na niche.',
    'biz-li1':'Pokročilé filtre: niche, sledovatelia, miera angažovanosti, platforma, krajina',
    'biz-li2':'Len overení influenceri — žiadne falošné zhliadnutia, žiadni kúpení sledovatelia',
    'biz-li3':'Plať len za výsledky s affiliate kampaňami',
    'biz-li4':'Analytika v reálnom čase — sleduj zobrazenia, kliknutia, konverzie',
    'biz-learn':'Zistiť viac pre firmy →',
    'infl-tease-title':'Premeň svoju vášeň na príjem',
    'infl-tease-sub':'Nepotrebuješ milióny sledovateľov. Ak máš lojálne publikum v konkrétnom niche, IBBI ťa spája s firmami, ktoré skutočne potrebujú tvoj hlas.',
    'infl-li1':'Prehľadávaj kampane zodpovedajúce tvojmu niche automaticky',
    'infl-li2':'Viacero modelov zárobku — affiliate, barter, fixný, hybrid',
    'infl-li3':'Sleduj všetky príjmy a výkonnosť na jednom mieste',
    'infl-li4':'Priama peňaženka s výbermi kedykoľvek',
    'infl-learn':'Zistiť viac pre influencerov →',
    // Features
    'feat-tag':'Funkcie platformy','feat-title':'Všetko, čo potrebuješ, nič navyše',
    'feat-sub':'IBBI je postavené na rýchlosti a jednoduchosti. Nastav kampaň za minúty, nie dni.',
    'feat-1-title':'Inteligentné párovanie','feat-1-desc':'Algoritmus spája firmy s tvorcami na základe niche, kvality publika, miery angažovanosti a preferencií typu kampane.',
    'feat-2-title':'Overení tvorcovia','feat-2-desc':'Každý influencer prepojí sociálne siete počas registrácie. Overujeme skutočnú angažovanosť a autentičnosť.',
    'feat-3-title':'Analytika v reálnom čase','feat-3-desc':'Sleduj zobrazenia, kliknutia, konverzie a príjmy pre každú kampaň. Performance dashboardy pre obe strany v reálnom čase.',
    'feat-4-title':'Integrované správy','feat-4-desc':'Dohaduj, zosúlaďuj a komunikuj priamo na platforme. Žiadne e-mailové reťazce ani stratené správy na WhatsApp.',
    'feat-5-title':'Priama peňaženka','feat-5-desc':'Influenceri dostávajú príjmy priamo na IBBI peňaženku. Žiadaj výbery kedykoľvek — bez čakania na manuálne faktúry.',
    'feat-6-title':'Systém hodnotenia','feat-6-desc':'Obe strany sa navzájom hodnotia po každej spolupráci. Buduje dôveru a pomáha budúcim partnerom robiť lepšie rozhodnutia.',
    // Comparison
    'cmp-tag':'vs. konkurencia','cmp-title':'Prečo IBBI predbieha alternatívy',
    'cmp-sub':'Upfluence, Aspire a Colabstr sú drahé, ťažko použiteľné a nezaručujú výsledky. IBBI bolo postavené pre malé a stredné podniky — dostupné, transparentné, orientované na výsledky.',
    'cmp-col-feature':'Funkcia','cmp-r1':'Zadarmo pre influencerov','cmp-r1-ibbi':'✓ Vždy zadarmo',
    'cmp-r2':'Model platby za výsledok','cmp-r3':'Počiatočná cena / mesiac','cmp-r3-ibbi':'Zadarmo / Freemium',
    'cmp-r4':'Overenie influencera','cmp-r4-ibbi':'✓ Automatizované',
    'cmp-r5':'Vstavaná analytika','cmp-r5-ibbi':'✓ Pokročilá',
    'cmp-r6':'Priame správy','cmp-r7':'Vstavaná peňaženka / výplaty',
    'cmp-r8':'Priateľské pre malé firmy','cmp-r8-ibbi':'✓ Naše jadro','cmp-enterprise':'✗ Enterprise',
    // Landing CTA
    'land-cta-title':'Pripravení rásť spolu?',
    'land-cta-sub':'Pridaj sa k stovkám firiem a tvorcov, ktorí spolupracujú na IBBI. Začni zadarmo, bez platobnej karty.',
    'cta-start-free':'Začni zadarmo',
    // Pricing
    'price-tag':'Cenník','price-title':'Začni zadarmo. Škáluj, keď si pripravený.',
    'price-sub':'IBBI používa freemium model — dostatočne silný na dosiahnutie prvých výsledkov zadarmo, s plnými funkciami pre ďalší rast.',
    'price-free-name':'Zadarmo','price-free-period':'Navždy',
    'price-free-f1':'✓ 1 aktívna kampaň','price-free-f2':'✓ Pokročilá analytika',
    'price-free-f3':'✓ Objavovanie tvorcov','price-free-f4':'✓ Priame správy',
    'price-free-f5':'✓ Reporty výkonnosti kampaní','price-free-f6':'✓ Vstavaná peňaženka &amp; výplaty',
    'price-free-btn':'Začať','price-pro-badge':'Obľúbené','price-pro-period':'/mesiac',
    'price-pro-f1':'✓ Neobmedzené kampane','price-pro-f2':'✓ Pokročilá analytika',
    'price-pro-f3':'✓ Prioritné párovanie','price-pro-f4':'✓ Reporty výkonnosti kampaní',
    'price-pro-f5':'✓ Dedikovaný account manager','price-pro-f6':'✓ Vlastné typy kampaní',
    'price-pro-f7':'✓ Prístup k API','price-pro-btn':'Získať Pro',
    // Footer
    'footer-desc':'Inteligentná platforma spájajúca overených tvorcov obsahu s firmami, ktoré zodpovedajú ich niche. Transparentná, dátovo riadená, dostupná.',
    'footer-platform':'Platforma','footer-campaigns':'Kampane','footer-legal':'Právne',
    'footer-terms':'Podmienky použitia','footer-privacy':'Ochrana súkromia','footer-cookies':'Cookies',
    'footer-rights':'© 2026 IBBI. Všetky práva vyhradené.',
    'footer-made':'Vytvorené s ❤ pre tvorcov &amp; značky',
    // For influencers page
    'ip-hero-tag':'Pre tvorcov obsahu','ip-hero-h1':'Premeň svoju vášeň<br>na skutočný príjem',
    'ip-hero-sub':'Nepotrebuješ 1M sledovateľov. Ak máš angažované, lojálne publikum v konkrétnom niche — firmy hľadajú presne teba.',
    'ip-hero-cta1':'Registruj sa zadarmo',
    'problem-tag':'Problém','ip-prob-title':'Nájsť spolupráce so značkami by nemalo byť také ťažké',
    'ip-earn-tag':'Zarábaj po svojom','ip-earn-title':'4 spôsoby, ako monetizovať svoju komunitu',
    'ip-earn-sub':'Vyber si model, ktorý najlepšie funguje pre tvoj štýl a publikum.',
    'ip-aff-desc':'Propaguj produkt so svojím unikátnym odkazom. Zarob províziu za každý predaj alebo kliknutie. Najlepšie pre tvorcov s konvertujúcim publikom.',
    'ip-aff-tag':'Na základe provízií',
    'ip-fixed-desc':'Dohovor sa na honorári za príspevok, story alebo video. Platba je garantovaná bez ohľadu na výsledky. Najlepšie pre tvorcov s prémiovým obsahom.',
    'ip-fixed-tag':'Garantovaná platba',
    'ip-barter-desc':'Dostaneš produkt, ktorý ťa skutočne zaujíma, a recenzuješ ho poctivo. Žiadna hotovosť — vyberáš si značky, ktoré sa zhodujú s tvojimi hodnotami a obsahom.',
    'ip-hybrid-desc':'Základný fixný honorár plus provízia. Dostaneš garantované minimum plus bonus za silný výkon. Môžeš ho tiež skombinovať s barterom.',
    'ip-hybrid-tag':'Fixná + provízia',
    'ben-tag':'Výhody','ip-ben-title':'Všetko postavené okolo tvojho úspechu',
    'ip-ben-1t':'Kampane zacielené na tvoje niche','ip-ben-1d':'Zobrazujú sa ti len kampane relevantné pre tvoj obsah. Fitness tvorca? Len fitness značky. Food bloger? Len food firmy.',
    'ip-ben-2t':'Performance dashboard','ip-ben-2d':'Sleduj zobrazenia, kliknutia, konverzie a zárobky pre každú kampaň v reálnom čase.',
    'ip-ben-3t':'Priama peňaženka &amp; výbery','ip-ben-3d':'Všetky zárobky idú priamo na tvoju IBBI peňaženku. Požiadaj o výber kedykoľvek — bankový prevod do 3 pracovných dní.',
    'ip-ben-4t':'Buduj svoju reputáciu','ip-ben-4d':'Každá úspešná spolupráca ti prinesie hodnotenie. Influenceri s vysokým hodnotením dostávajú prednostné párovanie s top značkami.',
    'ip-ben-5t':'Vstup zadarmo','ip-ben-5d':'Vstup na IBBI je zadarmo — žiadne predplatné, žiadne skryté poplatky. Berieme malú 10% platformovú províziu len zo zárobkov získaných cez platformu.',
    'ip-ben-6t':'Priama komunikácia','ip-ben-6d':'Chatuj priamo so firmami na platforme. Dohaduj podmienky, pýtaj sa, potvrdzuj deliverables — všetko na jednom mieste.',
    'ip-old1-title':'Starý spôsob','ip-old1-desc':'Posielanie správ firmám, ktoré nikdy neodpíšu. Ignorovanie alebo smiešne podmienky. Hodiny zbytočného oslovovania — kým tvoj obsah ďalej rastie.',
    'ip-new1-title':'IBBI spôsob','ip-new1-desc':'Firmy prídu za tebou. Náš algoritmus zobrazí tvoj profil značkám vo tvojom niche. Jeden klik na prijatie, vstavaná komunikácia a platba priamo na tvoju peňaženku.',
    'ip-old2-title':'Žiadna transparentnosť','ip-old2-desc':'Nikdy nevieš, či je značka seriózna. Platba vopred? Riskantné. Platba potom? Často ťa ignorujú. Žiadna zmluva, žiadna ochrana, žiadna možnosť sťažnosti.',
    'ip-new2-title':'Plná ochrana','ip-new2-desc':'Každá firma na IBBI je registrovaná a hodnotená inými influencermi. Pozri si hodnotenie pred tým, ako sa rozhodneš. Podmienky kampane sú uzamknuté v platforme.',
    'ip-cta-title':'Začni zarábať so svojím obsahom ešte dnes',
    'ip-cta-sub':'Vstup zadarmo. Prepoj sociálne siete, dokonči profil a začni dostávať pozvánky do kampaní do 24 hodín.',
    'ip-cta-btn':'Vytvor si bezplatný účet',
    'ip-niche-tag':'Pre koho je IBBI','ip-niche-title':'Nemusíš byť slávny',
    'ip-niche-sub':'IBBI je vytvorené pre tvorcov, ktorí sú hlboko spojení s konkrétnou komunitou — nielen pre tých s najväčším počtom sledovateľov.',
    'ip-niche-1t':'Fitness a zdravie','ip-niche-1d':'Osobní tréneri, výživoví poradcovia, inštruktori jogy — značky milujú niche fitness tvorcov so skutočnými, angažovanými sledovateľmi.',
    'ip-niche-2t':'Jedlo a životný štýl','ip-niche-2d':'Recenzenti reštaurácií, domáci kuchári, fotografovia jedla — lokálne aj národné potravinárske značky vždy hľadajú autentické hlasy.',
    'ip-niche-3t':'Ekológia a udržateľnosť','ip-niche-3d':'Tvorcovia zeleného životného štýlu, zero-waste aktivisti — eko-značky cielene vyhľadávajú micro-influencerov s vášnivým, uvedomelým publikom.',
    'ip-niche-4t':'Krása a starostlivosť o seba','ip-niche-4d':'Makeupartistky, nadšenci skincare, nail techničky — krása je jedna z najlepšie platených niche pre autentické recenzie produktov.',
    'ip-niche-5t':'Technológie a gaming','ip-niche-5d':'Recenzenti, streameri, tvorcovia návodov — technologické firmy si cenia tvorcov, ktorí vedia vysvetliť produkty znalostnému publiku.',
    'ip-niche-6t':'Cestovanie a dobrodružstvo','ip-niche-6d':'Cestovatelia-blogeri, fotografovia destinácií — cestovné kancelárie a turistické značky potrebujú autentické zážitky od skutočných objaviteľov.',
    // For businesses page
    'bp-hero-tag':'Pre firmy &amp; značky','bp-hero-h1':'Influencer marketing,<br>ktorý skutočne funguje',
    'bp-hero-sub':'Prestaň platiť €2 000/mesiac za platformy, ktoré neprinášajú výsledky. IBBI ťa spája s overenými tvorcami vo tvojom niche — a platíš len za skutočné výsledky.',
    'bp-hero-cta1':'Začni zadarmo','bp-prob-title':'Prečo väčšina influencer marketingu zlyhá',
    'bp-hiw-title':'Od registrácie po prvú kampaň za niekoľko minút',
    'bp-step1-title':'Vytvor si firemný profil',
    'bp-step1-desc':'Registruj sa a popíš svoju značku a cieľové niche. Čím viac detailov poskytneš, tým lepšie párovanie pre teba.',
    'bp-step2-title':'Objavuj &amp; pozývaj tvorcov',
    'bp-step2-desc':'Prehľadávaj databázu overených tvorcov. Filtruj podľa niche, sledovateľov, angažovanosti a platformy. Posielajte pozvánky priamo v aplikácii.',
    'bp-step3-title':'Spusti &amp; sleduj výsledky',
    'bp-step3-desc':'Vytvor kampaň, nastav podmienky a typ odmeny. Sleduj každé zobrazenie, kliknutie a konverziu z analytics dashboardu.',
    'bp-ben-title':'Postavené pre malé &amp; stredné firmy',
    'bp-ben-sub':'Žiadne podnikové zmluvy. Žiadne predplatné po €2 000/mesiac. IBBI ti dáva nástroje veľkej platformy za rozumnú cenu.',
    'bp-ben-1t':'Pokročilé objavovanie tvorcov','bp-ben-1d':'Hľadaj podľa niche, platformy, rozsahu sledovateľov, miery angažovanosti, krajiny a kompatibility typu kampane.',
    'bp-ben-2t':'Campaign analytics','bp-ben-2d':'Dáta v reálnom čase o zobrazeniach, návštevníkoch webu, konverziách a nákladoch na získanie zákazníka.',
    'bp-ben-3t':'Ochrana pred podvodom','bp-ben-3d':'Automatická detekcia falošných sledovateľov a kúpenej angažovanosti. Každý tvorca je hodnotený na autentičnosť pred vstupom na platformu.',
    'bp-ben-4t':'Flexibilné platobné modely','bp-ben-4d':'Vyber si z affiliate (platba za výsledok), fixného honoráru, barteru alebo hybridného modelu.',
    'bp-ben-5t':'Hodnotenia tvorcov','bp-ben-5d':'Pozri hodnotenia od iných firiem ešte pred pozvaním tvorcu. Komunitou overená spoľahlivosť, nielen počty sledovateľov.',
    'bp-ben-6d':'Píš tvorcom priamo na IBBI. Diskutuj podmienky, zdieľaj briefy, kontroluj obsah — bez externých nástrojov.',
    'bp-prob1-t':'Falošná angažovanosť','bp-prob1-d':'Zaplatíš tvorcovi, postne, čísla vyzerajú skvele — ale tieto zobrazenia a lajky boli zakúpené. Žiadni skutoční zákazníci, žiadna skutočná návratnosť. Len premárnený rozpočet.',
    'bp-sol1-t':'Iba overení','bp-sol1-d':'Každý influencer na IBBI prepojí svoje sociálne účty za účelom overenia. Automaticky označujeme podozrivé miery angažovanosti, zakúpených sledovateľov a neautentický rast.',
    'bp-prob2-t':'Nesprávne publikum','bp-prob2-d':'Najväčší influencer v tvojej krajine nie je nevyhnutne ten správny pre tvoju značku. Dosah bez relevantnosti je len šum — a drahý šum.',
    'bp-sol2-t':'Cielená zhoda podľa niche','bp-sol2-d':'Filtruj podľa niche, platformy, počtu sledovateľov, miery angažovanosti, polohy a typu kampane. Nájdi tvorcov, ktorých publikum naozaj chce tvoj produkt.',
    'bp-prob3-t':'Zaplatiť vopred, nedostať nič','bp-prob3-d':'Tradičné influencer dohody vyžadujú platbu pred dodaním. Mnohí tvorcovia ignorujú, dodajú slabý obsah, alebo jednoducho nedosiahnu sľúbené výsledky.',
    'bp-sol3-t':'Affiliate kampane','bp-sol3-d':'S affiliate modelom IBBI platíš len vtedy, keď influencer dosiahne skutočné výsledky — kliky, registrácie alebo nákupy. Nulové riziko, maximálna návratnosť.',
    'bp-cta-title':'Pripravený nájsť dokonalých tvorcov?',
    'bp-cta-sub':'Pridaj sa k firmám, ktoré rastú vďaka autentickým influencer partnerstvám na IBBI. Začni zadarmo, bez platobnej karty.',
    'bp-cta-btn':'Vytvoriť firemný účet','bp-cta-login':'Mám už účet',
    // About us
    'au-hero-tag':'Náš príbeh','au-hero-h1':'Riešime problém<br>za 2 miliardy €',
    'au-hero-sub':'Malé firmy si nemôžu dovoliť podnikové influencer platformy. Influenceri majú problém nájsť dôveryhodné spolupráce so značkami. IBBI bolo postavené na vyriešenie oboch problémov.',
    'au-miss-tag':'Naša misia','au-miss-title':'Sprístupniť influencer marketing pre každého',
    'au-miss-p1':'Influencer marketing má celosvetovú hodnotu cez €20 miliárd — no väčšina jeho hodnoty je uzamknutá za drahými nástrojmi dostupnými len veľkým korporáciám.',
    'au-miss-p2':'Malé a stredné firmy majú skvelé produkty, ale nemajú marketingový tím. Micro a stredne veľkí influenceri majú lojálne publikum, ale nemajú jednoduchý spôsob, ako ho monetizovať. IBBI tieto dve strany spája.',
    'au-miss-p3':'Veríme, že lokálna fitness značka by mala vedieť spolupracovať s lokálnym fitness tvorcom rovnako ľahko, ako Nike pracuje s Cristianom Ronaldom. To je to, čo budujeme.',
    'au-prob-tag':'Problém, ktorý riešime','au-prob-title':'Dve strany, jeden nefunkčný systém',
    'au-prob-sub':'Obom firmám aj influencerom chýbali adekvátne riešenia. Počúvali sme obe strany predtým, ako sme čokoľvek začali budovať.',
    'au-val-tag':'Naše hodnoty','au-val-title':'Čomu veríme',
    'val-1t':'Transparentnosť','val-1d':'Veríme, že každá spolupráca by mala byť založená na skutočných dátach. Žiadne skryté metriky, žiadne falošné čísla, žiadne prekvapenia.',
    'val-2t':'Jednoduchosť','val-2d':'Silný nemusí znamenať komplikovaný. Každá funkcia na IBBI je navrhnutá tak, aby ju každý pochopil a použil za pár sekúnd.',
    'val-3t':'Férovosť','val-3d':'Firmy aj tvorcovia si zaslúžia spravodlivé podmienky. IBBI je neutrálna pôda, kde vyhrávajú obe strany.',
    'val-4t':'Výsledky na prvom mieste','val-4d':'Úspech meriame tým, či naši používatelia rastú — nie tým, koľko funkcií sme vydali. Výsledky nad aktivitu.',
    'val-5t':'Dôvera','val-5d':'Každý overovací krok, každý systém hodnotenia, každá kontrola podvodov — všetko je postavené na to, aby bola každá interakcia dôveryhodná.',
    'val-6t':'Dostupnosť','val-6d':'Skvelé marketingové nástroje by nemali vyžadovať rozpočet €2 000. IBBI je postavené pre firmy akejkoľvek veľkosti, na akomkoľvek trhu.',
    'au-road-tag':'Roadmap','au-road-title':'Kam smerujeme',
    'au-road-sub':'Sme len na začiatku. Tu je to, čo prichádza do IBBI v ďalších fázach.',
    'au-quote-text':'"Ako Tinder,<br>ale pre značky<br>&amp; tvorcov"',
    'au-quote-sub':'Náš zakladajúci koncept — inteligentné párovanie medzi správnymi partnermi',
    'au-biz-pain-h':'Problémy firiem','au-infl-pain-h':'Problémy influencerov',
    'au-biz-p1-t':'Nedôvera v autenticitu','au-biz-p1-d':'Ako zistíš, že sledovatelia influencera sú skutoční? Falošné metriky premrhajú tisíce z rozpočtu bez akejkoľvek návratnosti.',
    'au-biz-p2-t':'Vysoké náklady na platformy','au-biz-p2-d':'Existujúce platformy začínajú na €2 000/mesiac — úplne mimo dosahu väčšiny malých firiem.',
    'au-biz-p3-t':'Nepresné párovanie','au-biz-p3-d':'Nájsť influencera, ktorý osloví práve tvoje cieľové publikum, je časovo náročné, drahé a často nepresné.',
    'au-infl-p1-t':'Ignorovanie','au-infl-p1-d':'Malí a stredne veľkí tvorcovia strávia hodiny cold outreachom na firmy, ktoré nikdy neodpovedia. Demotivujúce a časovo náročné.',
    'au-infl-p2-t':'Riziko platby','au-infl-p2-d':'Bez bezpečného platobného systému tvorcovia často odvedú prácu a nikdy nedostanú zaplatené. Žiadna ochrana, žiadne vynucovanie zmluvy.',
    'au-infl-p3-t':'Žiadne analytiky','au-infl-p3-d':'Väčšina tvorcov netuší, ktoré spolupráce skutočne prinášajú výsledky. Bez dát nie je lepšia vyjednávacia pozícia.',
    'au-road-p1-t':'Fáza 1 — Teraz','au-road-p1-d':'Základná platforma: registrácia, tvorba kampaní, objavovanie tvorcov, správy, základné analytiky, peňaženka a výplaty.',
    'au-road-p2-t':'Fáza 2 — Q3 2026','au-road-p2-d':'Pokročilý analytický dashboard, sociálne prihlásenie (Google, Meta), automatizované výkonnostné reporty, mobilná aplikácia.',
    'au-road-p3-t':'Fáza 3 — Q1 2027','au-road-p3-d':'AI-powered návrhy kampaní, viacjazyčná podpora, enterprise verzia, API pre vlastné integrácie.',
    'au-road-p4-t':'Fáza 4 — 2027+','au-road-p4-d':'Medzinárodná expanzia, marketplace pre obsahové aktíva, pokročilé AI na detekciu podvodov, akadémia tvorcov.',
    'au-cta-title':'Pridaj sa k nám na tejto ceste',
    'au-cta-sub':'Či si tvorca, ktorý chce monetizovať svoju vášeň, alebo firma, ktorá hľadá autentický marketing — IBBI je pre teba.',
    // Auth
    'reg-tag':'Vytvoriť účet','reg-title':'Ako sa chceš registrovať?',
    'reg-sub':'Vyber si rolu — môžeš ju vždy neskôr zmeniť v nastaveniach.',
    'reg-infl-desc':'Tvorím obsah a chcem spolupracovať so značkami na kampaniach &amp; odmenách.',
    'reg-infl-btn':'Registrovať sa ako influencer','reg-biz-name':'Firma',
    'reg-biz-desc':'Zastupujem značku alebo firmu a chcem nájsť influencerov pre kampane.',
    'reg-biz-btn':'Registrovať sa ako firma',
    'reg-login-link':'Už máš účet? <a onclick="go(\'login\')" style="color:var(--blue);cursor:pointer;font-weight:600">Prihlásiť sa</a>',
    'login-title':'Vitaj späť','login-sub':'Prihlás sa do svojho účtu','login-btn':'Prihlásiť sa',
    'login-signup-link':'Nemáš účet? <a onclick="go(\'signup-role\')" style="color:var(--blue);cursor:pointer;font-weight:600">Zaregistruj sa zadarmo</a>',
    // App portal topbar
    'app-biz-portal':'Firemný <span style="color:var(--blue)">portál</span>',
    'app-infl-portal':'Influencer <span style="color:var(--blue)">portál</span>',
    // Dashboard stats
    'd-active-camps':'Aktívne kampane','d-total-reach':'Celkový dosah',
    'd-conversions':'Konverzie','d-total-spent':'Celkové náklady',
    'd-total-earnings':'Celkové zárobky','d-followers':'Sledovatelia',
    'd-avg-er':'Priem. angažovanosť','d-across-camps':'Naprieč všetkými kampaňami',
    'd-all-time':'Za celú dobu','d-camp-spend':'Výdaje na kampane',
    'd-lifetime':'Zárobky za celú dobu','d-across-plat':'Naprieč platformami',
    'd-er-label':'Miera angažovanosti','d-total-convs':'Celkové konverzie',
    'd-roas':'Návratnosť výdavkov','d-camp-budget':'Použitý budget',
    // Dashboard sections
    'd-recent-camps':'Nedávne kampane','d-view-all':'Zobraziť všetky',
    'd-quick-actions':'Rýchle akcie','d-create-camp':'Vytvoriť kampaň',
    'd-discover-infls':'Nájsť influencerov','d-view-analytics':'Zobraziť štatistiky',
    'd-wallet-bal':'Zostatok v peňaženke','d-avail-bal':'Dostupný zostatok',
    'd-top-up':'Dobiť','d-top-infls':'Top influenceri tohto mesiaca',
    'd-discover-more':'Objaviť ďalších','d-my-camps':'Moje kampane',
    'd-browse-more':'Prehľadávať ďalej','d-browse-camps':'Prehľadávať kampane',
    'd-edit-profile':'Upraviť profil','d-wallet-lbl':'Peňaženka',
    'd-avail-withdraw':'Dostupné na výber','d-withdraw':'Vybrať',
    'd-rec-camps':'Odporúčané kampane','d-see-all':'Zobraziť všetky',
    'd-apply-now':'Prihlásiť sa','d-due':'Uzávierka',
    // Table headers
    'th-campaign':'Kampaň','th-type':'Typ','th-status':'Stav',
    'th-reach':'Dosah','th-spent':'Náklady','th-brand':'Značka',
    'th-reward':'Odmena','th-conversions':'Konverzie','th-roas':'ROAS',
    // Campaigns
    'c-my-camps':'Moje kampane','c-total-label':'kampaní celkovo',
    'c-new':'Nová kampaň','c-create-new':'Vytvoriť novú kampaň',
    'c-launch':'Spustiť kampaň','c-draft':'Uložiť ako koncept','c-cancel':'Zrušiť',
    'c-form-name':'Názov kampane','c-form-type':'Typ kampane',
    'c-form-budget':'Celkový budget (€)','c-form-reward':'Odmena na influencera (€)',
    'c-form-niche':'Cieľové niche','c-form-deadline':'Uzávierka',
    'c-form-brief':'Brief kampane',
    'c-form-commission':'Miera provízie (%)','c-form-barter-desc':'Barter produkt / služba',
    'c-form-desc':'Popis kampane','c-form-payout-metric':'Spôsob vyplácania',
    'c-form-target-niches':'Cieľové nichy','c-form-niche-sub':'vyber všetky relevantné',
    'c-form-deadline-sub':'voliteľné — prebieha do vyčerpania budgetu',
    'c-form-combine-types':'Kombinovať typy kampaní','c-form-combine-sub':'vyber aspoň 2',
    'c-applied-badge':'Prihlásená','c-chat':'Chat','c-ask':'Opýtať sa',
    'c-rate-brand':'★ Ohodnotiť značku','c-infl-available':'kampane dostupné',
    'c-applied-count':'prihlásených','c-view-campaigns':'Zobraziť kampane',
    // Discover
    'dis-infls-title':'Objavovanie influencerov','dis-brands-title':'Objavovanie značiek',
    'dis-infls-sub':'overených tvorcov nájdených','dis-brands-sub':'aktívne hľadajú spoluprácu',
    'f-all-types':'Všetky typy','f-all-industries':'Všetky odvetvia',
    'f-all-niches':'Všetky niche','f-all-sizes':'Všetky veľkosti','f-any-platform':'Ľubovoľná platforma',
    'f-search-camps':'Hľadať kampane…','f-search-brands':'Hľadať značky…',
    'f-search-infls':'Hľadať meno alebo @handle…',
    'f-sort-followers':'Zoradiť: Sledovatelia ↓','f-sort-er':'Zoradiť: ER ↓',
    'f-sort-rating':'Zoradiť: Hodnotenie ↓','f-sort-price':'Zoradiť: Cena ↑',
    // Infl card labels
    'ic-campaigns':'Kampane','ic-rating':'Hodnotenie','ic-message':'Správa','ic-invite':'Pozvať',
    // Analytics
    'an-total-reach':'Celkový dosah','an-total-convs':'Celkové konverzie',
    'an-total-spent':'Celkové náklady','an-roas':'ROAS',
    'an-perf-title':'Mesačný dosah a konverzie','an-mix-title':'Mix kampaní',
    'an-camp-title':'Porovnanie výkonnosti kampaní',
    'an-infl-title':'Výkonnosť influencerov',
    // Wallet
    'w-avail-bal':'Dostupný zostatok','w-total-topped':'Celkovo dobité:',
    'w-top-up-title':'Dobiť peňaženku','w-topup-sub':'Prostriedky sa pridajú okamžite po platbe. Minimum 10 €.',
    'w-pay-card':'Zaplatiť kartou →','w-request':'Požiadať o výplatu',
    'w-active-camps':'Aktívne kampane',
    // Conversations
    'msg-conversations':'Konverzácie','msg-no-convs':'Žiadne konverzácie.',
    'msg-send':'Odoslať','msg-placeholder':'Napíš správu…',
    'msg-active-infl':'Aktívny influencer','msg-active-biz':'Aktívna firma',
    'msg-no-convs-biz':'Zatiaľ žiadne konverzácie.<br>Pozvi influencera a začni.',
    'msg-select-conv':'Vyber konverzáciu','msg-active-brand':'Značka',
    'msg-no-msgs-yet':'Zatiaľ žiadne správy. Pozdrav! 👋',
    // Messages filter tabs
    'msg-filter-all':'Všetky','msg-filter-unread':'Neprečítané','msg-filter-starred':'Značky','msg-filter-creators':'Tvorcovia',
    'msg-collaborate':'Spolupracovať','msg-attach-title':'Priložiť súbor',
    // FindUser modal
    'fu-placeholder':'Nájdi creator-a, značku alebo @handle…',
    'fu-filters-btn':'Filtre','fu-filter-all':'Všetci','fu-filter-influencers':'Influencery','fu-filter-brands':'Firmy',
    'fu-recent-searches':'Posledné vyhľadávania','fu-popular-cats':'Populárne kategórie',
    'fu-recommended':'Odporúčaní pre teba','fu-results-for':'Výsledky pre',
    'fu-searching':'Hľadám…','fu-no-results':'Nič sa nenašlo. Skús iné kľúčové slovo.',
    'fu-loading-recommended':'Načítavam odporúčania…','fu-login-required':'Prihláste sa pre vyhľadávanie.',
    'fu-nav-hint':'navigácia','fu-open-hint':'otvoriť','fu-close-hint':'zavrieť',
    'fu-invite-email':'Pozvať e-mailom','fu-write-btn':'Napísať',
    'fu-role-creator':'Creator','fu-role-brand':'Brand','fu-followers-label':'sledovateľov',
    // App tabs
    'tab-performance':'Výkonnosť','tab-campaigns':'Kampane','tab-collaboration':'Spolupráca',
    'tab-revenue':'Zárobky','tab-overview':'Prehľad','tab-transactions':'Transakcie','tab-payouts':'Výplaty',
    // Status badges
    'status-active':'Aktívna','status-paused':'Pozastavená','status-completed':'Ukončená','status-draft':'Koncept',
    // Campaigns detail & misc
    'c-applications':'Prihlášky','c-loading':'Načítava sa…','c-select-conv':'Vyber konverzáciu',
    'c-applicants':'prihlásených','c-reward-label':'Odmena','c-due-label':'Uzávierka',
    // Profile
    'prof-edit-btn':'Upraviť profil','prof-save':'Uložiť zmeny','prof-cancel':'Zrušiť',
    'prof-edit-biz':'Upraviť firemný profil','prof-edit-infl':'Upraviť svoj profil',
    'prof-about':'O firme','prof-about-me':'O mne',
    'prof-about-placeholder':'Klikni na Upraviť profil a pridaj popis firmy.',
    'prof-active-camps':'Aktívne kampane','prof-no-active-camps':'Zatiaľ žiadne aktívne kampane.',
    'prof-reviews':'Recenzie od influencerov','prof-no-reviews':'Zatiaľ žiadne recenzie.',
    'prof-camps-run':'Kampane','prof-infls-worked':'Spolupráce',
    'prof-rating-label':'Hodnotenie','prof-reviews-count':'Recenzie',
    'prof-followers':'Sledovatelia','prof-avg-er':'Priem. ER','prof-campaigns':'Kampane',
    'prof-connected-platforms':'Prepojené platformy','prof-no-platforms':'Zatiaľ žiadne platformy.',
    'prof-add-platforms':'Pridaj platformy v Nastaveniach →',
    'prof-campaign-stats':'Štatistiky kampaní','prof-pricing':'Cenník',
    'prof-price-per-post':'Cena za príspevok','prof-no-pricing':'Cena nie je nastavená.',
    'prof-set-price':'Nastav cenový rozsah v Nastaveniach →',
    'prof-camps-applied':'Prihlásené kampane','prof-camps-completed':'Ukončené kampane',
    'prof-total-earnings':'Celkové zárobky','prof-avg-er-rate':'Priem. miera angažovanosti',
    'prof-verified':'✓ Overený','prof-loading':'Načítava sa profil…',
    // Settings field labels
    'fld-company-name':'Názov firmy','fld-industry':'Odvetvie','fld-website':'Webstránka',
    'fld-country':'Krajina','fld-phone':'Telefón','fld-work-email':'Pracovný email',
    'fld-full-name':'Celé meno','fld-username':'Používateľské meno','fld-niche':'Niche',
    'fld-price-range':'Cenový rozsah (napr. €200–500)','fld-bio':'Bio',
    'fld-about-company':'O vašej firme','fld-er':'Miera angažovanosti (%)','fld-followers':'Počet sledovateľov',
    'fld-first-name':'Meno','fld-last-name':'Priezvisko','fld-email':'Email','fld-primary-niche':'Primárne niche',
    // Settings sections
    'set-title':'Nastavenia účtu','set-company-profile':'Firemný profil','set-personal-info':'Osobné údaje',
    'set-notifications':'Notifikácie','set-security':'Zabezpečenie',
    'set-change-pwd':'Zmeniť heslo','set-enable-2fa':'Aktivovať 2FA',
    'set-danger-zone':'Nebezpečná zóna','set-delete-account':'Vymazať účet',
    'set-delete-warn-biz':'Vymazanie účtu je nevratné a odstráni všetky údaje o kampaniach.',
    'set-delete-warn-infl':'Vymazanie účtu natrvalo odstráni všetky tvoje údaje.',
    'set-loading':'Načítavajú sa nastavenia…',
    // Settings notification labels
    'notif-new-apps':'Nové prihlášky influencerov','notif-new-apps-desc':'Notifikácia pri prihlásení influencera do kampane',
    'notif-milestones':'Míľniky kampane','notif-milestones-desc':'Upozornenia na míľniky dosahu a konverzií',
    'notif-messages':'Notifikácie správ','notif-msg-biz-desc':'Nové správy od influencerov',
    'notif-weekly':'Týždenné reporty','notif-weekly-desc':'Prehľad výkonnosti každý pondelok',
    'notif-invites':'Nové pozvánky do kampaní','notif-invites-desc':'Značky, ktoré ťa priamo pozývajú',
    'notif-payment':'Platba prijatá','notif-payment-desc':'Keď sú zárobky pripísané na účet',
    'notif-deadline':'Pripomienky uzávierky kampane','notif-deadline-desc':'48h pred uzávierkou',
    'notif-weekly-perf':'Týždenný report výkonnosti','notif-weekly-perf-desc':'Prehľad každý pondelok',
    'notif-msg-infl-desc':'Nové správy od značiek',
    // Wallet extra
    'w-cancel':'Zrušiť','w-low-balance':'⚠ Nízky zostatok — dobite peňaženku, aby kampane bežali ďalej',
    'w-top-up-btn':'+ Dobiť','w-total-spent-lbl':'Celkové výdavky','w-total-topup-lbl':'Celkovo dobité',
    'w-lifetime':'Za celú dobu','w-all-time':'Za celú dobu','w-funded':'S aktívnym financovaním',
    'w-camps-run':'Kampane','w-monthly-spend':'Mesačné výdavky','w-spend-by-type':'Výdavky podľa typu kampane',
    'w-date':'Dátum','w-description':'Popis','w-amount':'Suma','w-status-col':'Stav',
    'w-total-earned-lbl':'Celkové zárobky','w-total-withdrawn-lbl':'Celkovo vybraté','w-to-bank':'Na bankový účet',
    'w-pending-label':'Čakajúce','w-processing':'Spracováva sa','w-completed':'Ukončené',
    'w-monthly-earnings':'Mesačné zárobky','w-payout-methods':'Spôsoby výplaty',
    'w-add-iban-section':'Pridať bankový účet (IBAN)','w-no-transactions':'Zatiaľ žiadne transakcie.',
    'w-request-withdrawal':'Žiadosť o výber','w-withdraw-btn':'Vybrať',
    'w-payout-history':'História výplat','w-no-payouts':'Zatiaľ žiadne výplaty.',
    'w-requested-badge':'Odoslané','w-add-iban-btn':'Pridať IBAN','w-camps-label':'Kampane',
    'w-iban-transfer':'Bankový prevod (IBAN)','w-pending-prefix':'Čakajúce:',
    'w-processing-suffix':'(spracováva sa)',
    'w-min-info':'Minimum: €50 · Spracovanie: 2–3 pracovné dni · Dostupné:',
    // Campaign detail modal
    'cd-no-brief':'Brief nebol zadaný.','cd-payout-method':'Spôsob vyplatenia',
    'cd-discount-code':'Zľavový kód + Provízia','cd-per-views':'Za zobrazenia',
    'cd-commission-rate':'Miera provízií','cd-reward-per-infl':'Odmena na influencera',
    'cd-product-service':'Produkt / Služba','cd-combined-types':'Kombinované typy',
    'cd-fixed-reward':'Fixná odmena','cd-barter-details':'Detaily bartera',
    'cd-budget':'Budget','cd-deadline-label':'Uzávierka','cd-niches':'Niche',
    'cd-brief-label':'Brief','cd-close':'Zavrieť','cd-applied':'✓ Prihlásená',
    // Analytics extra
    'an-camps-done':'Ukončené kampane','an-total-collabs':'Celkové spolupráce',
    // Discover filters
    'dis-no-infls':'Žiadni influenceri nenájdení','dis-no-infls-sub':'Skús upraviť filtre',
    'dis-no-brands':'Žiadne značky nenájdené','dis-no-brands-sub':'Skús upraviť filtre',
    'dis-brands-found':'značiek nájdených',
    // Influencer modal
    'modal-followers':'Sledovatelia','modal-eng-rate':'Angažovanosť','modal-campaigns':'Kampane',
    'modal-smart-match':'Smart Match skóre','modal-platforms':'Platformy',
    'modal-price-range':'Odhadovaný cenový rozsah',
    'modal-match-excellent':'Výborná zhoda s tvojimi aktívnymi kampaňami',
    'modal-match-good':'Dobrá zhoda — stojí za zváženie',
    'modal-match-moderate':'Stredná zhoda s tvojimi kampaňami',
    'modal-message':'Správa','modal-invite':'Pozvať',
    // Brand card
    'brand-active-camp':'aktívna kampaň','brand-active-camps':'aktívnych kampaní',
    // Toast messages
    'toast-profile-saved':'Profil uložený!','toast-company-req':'Názov firmy je povinný.',
    // Campaign modal
    'camp-modal-title':'Vytvoriť kampaň','camp-modal-sub':'Vyber typ a vyplň detaily',
    'camp-loading-apps':'Načítavajú sa prihlášky…',
    // Notifications panel
    'notif-panel-heading':'Oznámenia','notif-mark-all-read':'Označiť všetky',
    'notif-none':'Zatiaľ žiadne oznámenia','btn-close':'Zavrieť',
    // Change password modal
    'cp-subtitle':'Zadaj a potvrď svoje nové heslo.',
    'cp-update-btn':'Aktualizovať heslo',
    // 2FA modal
    'twofa-subtitle':'Naskenuj QR kód pomocou autentifikátora (Google Authenticator, Authy a pod.)',
    'twofa-verify-btn':'Overiť a aktivovať',
    // Rating modal
    'rating-title':'Ohodnoť spoluprácu','rating-click-star':'Klikni na hviezdu pre hodnotenie',
    'rating-submit-btn':'Odoslať hodnotenie',
    // Applications drawer
    'app-no-apps':'Zatiaľ žiadne prihlášky.','app-no-rating':'Bez hodnotenia',
    'app-accept':'Prijať','app-reject':'Odmietnuť',
    // Update stats modal
    'us-title':'Aktualizovať štatistiky kampane','us-reach-lbl':'Celkový dosah',
    'us-conv-lbl':'Konverzie','us-save-btn':'Uložiť štatistiky',
    // Role picker
    'role-pick-title':'Vyber typ účtu','role-pick-sub':'Máš oba typy účtov. Ako sa chceš prihlásiť?',
    'role-business':'Business','role-influencer':'Influencer',
    // Transaction descriptions
    'txn-topup':'Dobíjanie peňaženky','txn-camp-fund':'Financovanie kampane','txn-transaction':'Transakcia',
    'txn-earnings':'Zárobky','txn-withdrawal':'Výber',
    // Auth button states
    'btn-signing-in':'Prihlasovanie…','btn-creating-acc':'Vytváram účet…',
    'infl-signup-btn-lbl':'Pokračovať k overeniu →',
    'biz-signup-btn-lbl':'Vytvoriť účet a vstúpiť do dashboardu →',
    'btn-complete-setup':'Dokončiť nastavenie a prejsť na dashboard →',
    'btn-setting-up':'Nastavujem…',
    // Generic button states
    'btn-saving':'Ukladám…','btn-updating':'Aktualizujem…',
    'btn-verifying':'Overujem…','btn-disabling':'Deaktivujem…',
    'btn-stripe-redirect':'Presmerovanie na Stripe…','btn-pay-card':'Zaplatiť kartou →',
    'twofa-disable-btn':'Deaktivovať 2FA','twofa-manage-btn':'Spravovať 2FA',
    // Validation errors
    'err-fill-fields':'Prosím vyplňte všetky polia.',
    'err-pwd-length':'Heslo musí mať aspoň 8 znakov.',
    'err-fill-required':'Prosím vyplňte všetky povinné polia.',
    'err-accept-terms':'Prosím súhlas s podmienkami poskytovania služieb.',
    'err-acct-exists-infl':'Influencer účet pre tento email už existuje. Prihlás sa cez login.',
    'err-acct-exists-biz':'Business účet pre tento email už existuje. Prihlás sa cez login.',
    'err-name-username':'Meno a používateľské meno sú povinné.',
    'err-camp-name-brief':'Názov kampane a brief sú povinné.',
    'err-pwds-no-match':'Heslá sa nezhodujú.',
    'err-6digit-code':'Zadajte 6-miestny kód.',
    // Campaign wizard
    'wiz-step-type':'Typ','wiz-step-details':'Detaily','wiz-step-budget':'Rozpočet',
    'wiz-step-audience':'Publikum','wiz-step-schedule':'Rozvrh','wiz-step-lbl':'Krok',
    'wiz-back':'Späť','wiz-next':'Pokračovať','wiz-save-draft':'Uložiť návrh','wiz-launch':'Spustiť',
    'wiz-s1-title':'Aký typ kampane?','wiz-s1-sub':'Vyber model spolupráce, ktorý zodpovedá tvojmu cieľu.',
    'wiz-s2-title':'Detaily kampane','wiz-s2-sub':'Daj kampani jasný názov a brief, aby tvorcovia vedeli čo potrebuješ.',
    'wiz-brief-hint':'znakov','wiz-brief-ph':'Popíš čo chceš aby tvorcovia robili, aký obsah vytvoriť a akékoľvek špeciálne požiadavky…',
    'wiz-s3-title':'Rozpočet a odmena','wiz-s3-sub':'Nastav rozpočet a spôsob odmeny pre tvorcov.',
    'wiz-cpm':'CPM sadzba (€ za 1 000 zobrazení)','wiz-product-value':'Hodnota produktu (€)',
    'wiz-max-creators':'Max. počet tvorcov','wiz-payout-method':'Spôsob odmeny',
    'wiz-budget-info':'Rozpočet je orientačný. Skutočné výdavky závisia od počtu prijatých tvorcov.',
    'wiz-s4-title':'Publikum a cielenie','wiz-s4-sub':'Definuj profil tvorcu a publikum, ktoré chceš osloviť.',
    'wiz-niches':'Niche','wiz-niches-hint':'Vyber všetky vhodné',
    'wiz-audience-size':'Veľkosť publika (followeri)','wiz-geo':'Geografické cielenie',
    'wiz-s5-title':'Rozvrh a deliverables','wiz-s5-sub':'Nastav časový harmonogram a očakávaný výstup obsahu.',
    'wiz-start-date':'Dátum začiatku','wiz-platforms':'Platformy','wiz-deliverables':'Deliverables',
    'wiz-launch-info':'Kampaň bude skontrolovaná a aktivovaná do 24 hodín.',
    'wiz-type-affiliate':'Affiliate','wiz-type-affiliate-sub':'Platba za výsledok',
    'wiz-type-fixed':'Fixná odmena','wiz-type-fixed-sub':'Pevný honorár',
    'wiz-type-barter':'Barter','wiz-type-barter-sub':'Výmena za produkt',
    'wiz-type-hybrid':'Hybrid','wiz-type-hybrid-sub':'Kombinovaný model',
    'wiz-payout-discount':'Zľavový kód','wiz-payout-views':'CPM / Zobrazenia',
    'wiz-payout-bank':'Bankový prevod','wiz-payout-crypto':'Krypto',
    'wiz-camp-name-label':'Názov kampane','wiz-camp-brief-label':'Brief',
    'wiz-budget-label':'Celkový rozpočet (€)','wiz-commission-label':'Percentuálna provízia (%)',
    'wiz-fixed-fee-label':'Fixný honorár na tvorcu (€)',
  }
};

function t(k) { return (T[LANG] && T[LANG][k] !== undefined) ? T[LANG][k] : (T.en[k] || k); }

function setLang(lang) {
  LANG = lang;
  localStorage.setItem('ibbi-lang', lang);
  const translations = T[lang];
  if (!translations) return;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[key] !== undefined) el.innerHTML = translations[key];
  });
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
  // Re-render active portal page so JS-rendered strings update
  if (typeof APP !== 'undefined' && APP.user) {
    const role = APP.profile?.role || '';
    if (role === 'business' && typeof bizPage === 'function' && typeof S !== 'undefined') {
      bizPage(S.bizPage || 'dashboard');
    } else if (role === 'influencer' && typeof inflPage === 'function' && typeof S !== 'undefined') {
      inflPage(S.inflPage || 'dashboard');
    }
  }
}

// Apply saved language on load
if (LANG !== 'en') {
  document.addEventListener('DOMContentLoaded', () => setLang(LANG));
  if (document.readyState !== 'loading') setLang(LANG);
}
